// AUTO-GENERATED by build-blogs.cjs — do not edit manually
import { BlogPost } from './types';

export const BLOG_POSTS: BlogPost[] = [
  {
    "id": "1",
    "slug": "building-an-india-civic-transparency-map-and-accidentally-turning-ai-into-my-co-developer",
    "title": "Building an India Civic Transparency Map (and accidentally turning AI into my co-developer)",
    "excerpt": "Have you ever wondered what it would be like if you could click on any district in India and instantly see all its public data? Things like local crime stati...",
    "content": [
      "Have you ever wondered what it would be like if you could click on any district in India and instantly see all its public data? Things like local crime statistics, ongoing court cases, or even details about infrastructure projects? That’s the idea that got me started on my latest project: building a civic transparency dashboard, a map where public data, usually buried in dusty government PDFs, could finally come to life. Sounds pretty straightforward, right? Well, it turns out \"straightforward\" in development often means \"an adventure full of surprises.\"",
      "My first big hurdle was figuring out the development environment. My laptop is decent, but for a project this ambitious, I wanted a setup where an AI agent could really stretch its legs and help build the entire stack without me constantly hand-holding. So, in a move that I now realize was a bit wild, I decided to run the whole thing inside Kaggle notebooks. Yes, Kaggle, the machine learning platform! The AI agent, primarily Claude Opus, was literally architecting and building a full-stack application within an environment designed for data science experiments, and surprisingly, it actually worked for a while until it became too unwieldy.",
      "That's when I shifted everything over to Google Colab, specifically for a T4 GPU and more room for the AI to operate. The vision was to let the agent roam free, creating files, installing dependencies, and spinning up servers while I just observed the beautiful chaos. And it absolutely delivered: at one point, the AI generated over 40 files in a single pass, including a React frontend with a map, a Node.js backend, a PostgreSQL database schema with PostGIS, a Python ETL pipeline, seed datasets, and even scripts to get everything running. It felt less like coding and more like supervising an incredibly enthusiastic, super-fast intern who never needed a coffee break. The funniest part? That T4 GPU I booked ended up doing precisely nothing for hours, just sitting there while the backend processed CSVs, ran SQL queries, and drew map layers, proving that for most data engineering, a GPU is completely useless.",
      "Once the application finally came to life, a major reality check hit me: the platform technically worked, but it looked incredibly empty. The map showed a few lonely dots, crime data existed for just a handful of districts, and court cases were almost nonexistent. It was essentially a skeleton, hinting at a much larger system that was supposed to be there. That’s when it truly clicked for me that the hardest part of building civic tech isn't the code or the architecture; it's the data itself.",
      "All the elegant APIs, the robust database, and the working frontend were powered by little more than demo samples: a mere 20 districts, 165 crime records, 25 court cases, and 30 infrastructure projects. For a country as vast and diverse as India, that’s practically nothing. So now, the next major phase of this project is less about writing new code and more about building sophisticated pipelines to ingest, normalize, and link real public datasets—crime statistics, court data, infrastructure projects, government spending—all tied directly to the districts on the map. The goal is to eventually enable anyone to click on a district and see comprehensive information like crime registrations, conviction rates, pending court cases, and public infrastructure projects, all in one transparent view.",
      "Working with AI agents like Claude Opus throughout this entire process has been the most interesting part. Sometimes they act like brilliant, hyper-efficient engineers, anticipating needs and building out complex modules. Other times, they’re like an overzealous detective, taking a simple \"ok\" as a directive to scan the entire workspace for bugs, rewriting backend routes, updating files, and evolving the project in directions I hadn’t even considered. It’s chaotic, occasionally a little ridiculous, but also genuinely amazing. This whole experience feels like a glimpse into the future of developer workflow, where coding isn't just about typing lines, but about orchestrating a powerful AI collaborator that sometimes builds half your project while your expensive GPU just watches, doing absolutely nothing. And honestly, it's still totally worth it."
    ],
    "date": "March 2026",
    "tags": [
      "AI",
      "Data Engineering",
      "Civic Tech",
      "Maps",
      "Claude Opus",
      "Developer Life"
    ],
    "readTime": "4 min read"
  },
  {
    "id": "2",
    "slug": "building-portfolio-with-react",
    "title": "How I Built This Portfolio with React & Vite",
    "excerpt": "When I decided to build a portfolio, I had a clear vision: it should be fast, visually striking, and showcase my work effectively. After considering various ...",
    "content": [
      "When I decided to build a portfolio, I had a clear vision: it should be fast, visually striking, and showcase my work effectively. After considering various options, I chose React with TypeScript and Vite as my build tool.",
      "The design philosophy was inspired by modern glass-morphism trends—translucent cards, subtle gradients, and animated backgrounds. Framer Motion handles all the animations, from the hero section's rotating text to the smooth page transitions.",
      "One interesting decision was using HashRouter instead of BrowserRouter. Since I'm hosting on InfinityFree (a free hosting service), I don't have control over server-side routing. Hash-based routing ensures all routes work without any .htaccess configuration.",
      "The GitHub integration was a fun challenge. I fetch live data from GitHub's REST API to display my repositories, languages, and activity. To handle rate limiting (60 requests/hour for unauthenticated requests), I implemented sessionStorage caching with a 10-minute TTL.",
      "For styling, Tailwind CSS was a no-brainer. Its utility-first approach lets me build responsive layouts quickly. The dark theme uses a carefully chosen palette of slate colors with indigo and cyan accents.",
      "Looking back, I'd do a few things differently: set up Tailwind as a proper PostCSS plugin instead of the CDN version, and add more comprehensive error handling. But overall, I'm proud of how it turned out. It's a living project that I continue to improve."
    ],
    "date": "March 2026",
    "tags": [
      "React",
      "Vite",
      "Web Dev",
      "Tutorial"
    ],
    "readTime": "2 min read"
  },
  {
    "id": "3",
    "slug": "my-coding-journey",
    "title": "My Coding Journey: From HTML to AI Agents",
    "excerpt": "It all started when I was 14. A curiosity about how websites work led me to open Notepad and type my first <html> tag. That simple act of creating something ...",
    "content": [
      "It all started when I was 14. A curiosity about how websites work led me to open Notepad and type my first <html> tag. That simple act of creating something from nothing—a heading that appeared in a browser—was all it took to get me hooked.",
      "The early days were filled with experiments: colorful pages with questionable design choices, buttons that didn't do anything, and lots of copy-pasting from tutorials. But every broken layout and every console error taught me something new.",
      "JavaScript was my first real challenge. Moving from static pages to interactive ones felt like unlocking a superpower. I built a calculator (Calculato Ready) and a music player—simple projects, but each one pushed my skills further.",
      "Then came Python, which opened up a whole new world beyond the browser. Scripts that automated tasks, programs that solved math problems, and eventually AI-powered applications. Linux became my playground for experimentation.",
      "Today, I'm building multi-agent AI systems, managing inventory apps with PHP and MySQL, and continuously exploring new technologies. The journey from that first HTML tag to here has been incredible, and I know the best is yet to come.",
      "If you're just starting out: embrace the struggle. Every error message is a lesson. Every project, no matter how small, is a step forward. Keep building, keep learning, and don't be afraid to experiment."
    ],
    "date": "March 2026",
    "tags": [
      "Personal",
      "Journey",
      "Beginner"
    ],
    "readTime": "2 min read"
  },
  {
    "id": "4",
    "slug": "the-daily-life-of-an-opus-addict",
    "title": "The Daily Life of an Opus Addict",
    "excerpt": "I recently asked Copilot, or more specifically, Claude Opus, to take a look at my portfolio website. Sounds like a pretty standard developer thing to do, rig...",
    "content": [
      "I recently asked Copilot, or more specifically, Claude Opus, to take a look at my portfolio website. Sounds like a pretty standard developer thing to do, right? Just a quick \"analyze my site and tell me what could be better.\" But what happened next was honestly a bit wild and made me realize something: I'm apparently a full-blown Opus addict. I'm talking about using the biggest, most powerful model for literally everything, from planning architecture and debugging complex code all the way down to making a simple text file or even just saying \"hi\" back to me – which probably cost a few rupees worth of compute for a single greeting.",
      "So, when I threw my portfolio at it, Opus didn't just casually glance; it went into absolute full-engineer mode. It started scanning my entire workspace, diving deep into file structures, components, routes, styles, you name it. The craziest part is that this whole intricate analysis was happening within the chat's context window, which is massive at around 128k tokens. Yet, somehow, we still managed to run out of context – not once, not twice, but four different times.",
      "Every single time, the conversation ballooned because the AI agent was constantly reasoning about the codebase and spitting out detailed improvement suggestions. When the context eventually died, Claude, being the absolute beast it is, would just restart the entire analysis process from scratch, rebuilding its understanding and the context window to about 30% after forgetting the older parts of our chat. It’s pretty funny when you think about it: I'm sitting there watching my premium requests slowly vanish as Opus basically performs a full engineering review of a simple portfolio site.",
      "But the peak of this whole experience happened a little later. After Opus gave me a bunch of output, I just typed \"ok\" as a normal human acknowledgment. What I didn't realize was that \"ok\" can apparently trigger autonomous debugging mode. Inside its thinking panel, it started processing, \"user wasn't satisfied...\" and then, without any further prompt, it literally began scanning my entire workspace again, reading files, checking code, actively looking for problems. It actually found some random, obscure bug in my portfolio that I probably never would have noticed, and then fixed it, replying with something like \"Here's the updated site.\" All of that, just because I said \"ok.\"",
      "Later, when I checked my usage dashboard, the reality hit even harder. More than 80% of my compute usage was dedicated to Claude Opus. That means I'm routinely deploying one of the strongest reasoning models available today for tasks like confirming things, making tiny edits, explaining stuff I mostly grasp already, and, yes, occasionally performing massive, multi-context-window workspace analyses. It's kind of ridiculous, but also genuinely amazing.",
      "In a weird way, though, this *is* the new developer workflow. Instead of just coding alone, you're essentially working alongside a ridiculously powerful AI teammate that sometimes just overthinks everything. You say \"ok,\" and it hears \"INITIATE FULL WORKSPACE INSPECTION.\" Somewhere in a data center, a GPU spins up just to make sure your portfolio website doesn't have a broken import, all triggered by a simple two-letter word. And honestly? Totally worth it."
    ],
    "date": "March 2026",
    "tags": [
      "AI",
      "Copilot",
      "Developer Life",
      "Claude Opus",
      "AI Stories"
    ],
    "readTime": "3 min read"
  }
];
