/**
 * Blog Compiler — reads all blogs/*.md and generates blogData.ts
 *
 * Usage: npm run blogs
 *
 * This is also auto-run before every build (see package.json "build" script).
 */

const fs = require('fs');
const path = require('path');

const BLOGS_DIR = path.join(__dirname, 'blogs');
const OUTPUT_FILE = path.join(__dirname, 'blogData.ts');

function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: raw.trim() };

  const metaBlock = match[1];
  const body = match[2].trim();
  const meta = {};

  for (const rawLine of metaBlock.split('\n')) {
    const line = rawLine.replace(/\r$/, '');
    const m = line.match(/^(\w+)\s*:\s*(.+)$/);
    if (!m) continue;
    let key = m[1];
    let value = m[2].trim();
    // Parse JSON arrays: ["a", "b"]
    if (value.startsWith('[')) {
      try { value = JSON.parse(value); } catch { /* keep as string */ }
    }
    // Strip surrounding quotes
    else if ((value.startsWith('"') && value.endsWith('"')) ||
             (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    meta[key] = value;
  }

  return { meta, body };
}

function estimateReadTime(text) {
  const words = text.split(/\s+/).length;
  return `${Math.max(1, Math.ceil(words / 200))} min read`;
}

function buildBlogData() {
  if (!fs.existsSync(BLOGS_DIR)) {
    console.log('\x1b[33m⚠\x1b[0m No blogs/ folder. Generating empty blogData.ts');
    fs.writeFileSync(OUTPUT_FILE,
      '// AUTO-GENERATED by build-blogs.cjs\nimport { BlogPost } from \'./types\';\n\nexport const BLOG_POSTS: BlogPost[] = [];\n',
      'utf8'
    );
    return;
  }

  const files = fs.readdirSync(BLOGS_DIR)
    .filter(f => f.endsWith('.md') && !f.includes('.backup-'))
    .sort();

  if (files.length === 0) {
    console.log('\x1b[33m⚠\x1b[0m No .md files in blogs/. Generating empty blogData.ts');
    fs.writeFileSync(OUTPUT_FILE,
      '// AUTO-GENERATED by build-blogs.cjs\nimport { BlogPost } from \'./types\';\n\nexport const BLOG_POSTS: BlogPost[] = [];\n',
      'utf8'
    );
    return;
  }

  const posts = files.map((file, idx) => {
    const raw = fs.readFileSync(path.join(BLOGS_DIR, file), 'utf8');
    const { meta, body } = parseFrontmatter(raw);

    const slug = path.basename(file, '.md');
    const paragraphs = body
      .split(/\n\s*\n/)
      .map(p => p.replace(/\r?\n/g, ' ').trim())
      .filter(p => p.length > 0);

    const title = meta.title || slug.replace(/-/g, ' ');
    const date = meta.date || 'Unknown';
    const tags = Array.isArray(meta.tags) ? meta.tags : [];
    const excerpt = paragraphs[0]
      ? (paragraphs[0].length > 160 ? paragraphs[0].slice(0, 157) + '...' : paragraphs[0])
      : '';

    return {
      id: String(idx + 1),
      slug,
      title,
      excerpt,
      content: paragraphs,
      date,
      tags,
      readTime: estimateReadTime(body),
    };
  });

  // Generate TypeScript
  const ts = `// AUTO-GENERATED by build-blogs.cjs — do not edit manually
import { BlogPost } from './types';

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, ts, 'utf8');
  console.log(`\x1b[32m✓\x1b[0m blogData.ts — ${posts.length} post(s) compiled`);
  posts.forEach(p => console.log(`  • ${p.title} (${p.readTime})`));
}

buildBlogData();
